name: Weekly Emails
on:
  schedule:
    - cron: "12 7 * * 5"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call api/cron/emails
        run: |
          curl --request GET \
          --url 'https://mywatchlists.watch/api/cron/emails' \
